"use strict";
const { MongoClient } = require("mongodb");
const { getPositionFromAddress } = require("./GetPositionFromAddress");
const { getAddressFromPosition } = require("./GetAddressFromPosition");

require("dotenv").config();
const { MONGO_URI } = process.env;

const options = {
  useNewUrlParser: true,
  useUnifiedTopology: true,
};

const addBloco = async (request, response) => {
  //the bloco id will be generated by uuid latter
  //the admId will be the user "sub" created by auth0
  //the admName will be the user "nickname" crated by auth0
  const { name, address, lat, lng, admId, admName } = request.body;
  if (!name || !admId || !admName) {
    return response
      .status(400)
      .json({
        status: 400,
        data: {
          name: name || "Missing name",
          admId: admId || "Missing admnistrator ID",
          admName: admName || "Missing admnistrator name",
        },
      });
  }

  //we need or the address or the coordinates
  if(!address && (!lat && !lng )){
    return response
      .status(400)
      .json({
        status: 400,
        data: {
          address: address || "Missing address",
          lat: lat || "Missing latitude",
          lng: lng || "Missing longitude",
        },
      });
  }

  if (!address && (typeof lat !== "number" || typeof lng !== "number")){
    return response.status(400).json({status: 400, message: "Latitude and Longitude must be numbers"})
  }

  const client = new MongoClient(MONGO_URI, options);

  try {

    await client.connect();
    const db = client.db("find-my-bloco");

    let blocoLat = lat;
    let blocoLng = lng;
    let newAddress = address;

    if(newAddress !== "NA"){
      const { lat, lng } = await getPositionFromAddress(address);
      blocoLat = lat;
      blocoLng = lng;
    } else if(newAddress === "NA"){
      const address = await getAddressFromPosition(blocoLat, blocoLng);
      newAddress = address;
    }

    //ADD FILTER FOR SPECIAL CARACTERES FOR THE NAME if possible
    const lowerCaseName = name.toLowerCase();
    const lowerCaseAddress = newAddress.toLowerCase();

    // getting the array of items from the user`s cart
    const hasBloco = await db.collection("blocos").findOne({ _id: lowerCaseName });

    //if there is no equal bloco, create a new one
    if (!hasBloco) {

      const newBloco = { _id: lowerCaseName, name: lowerCaseName, address: lowerCaseAddress, lat: blocoLat, lng: blocoLng, admId: admId, admName: admName };
      const resultAddBloco = await db.collection("blocos").insertOne(newBloco);
      
      //testing block
      resultAddBloco
      ? response.status(201).json({status: 201, data: newBloco, message:"Bloco successfully created!"})
      : response.status(400).json({ status: 400, message:"Bad request", data: newBloco});

    } else if (hasBloco) {
      response.status(409).json({ status: 409, message: "Bloco already exist" });
    }
  } catch (err) {
    (err) => console.log(err);
    response.status(500).json({ status: 500, message: "Server error" });
  } finally {
    client.close();
  }
};

module.exports = { addBloco };
