
export default {
  blocos: [
    {
      id: 'dear-girls',
      name: 'ausdh',
      address: 'asfsaf',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'utterly',
      name: 'qweq',
      address: 'qweqwr',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'angry-planet',
      name: 'wetwe',
      address: 'hdfhdf',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'technically-wrong',
      name: 'tyer',
      address: 'dfsdfs',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'orconomics',
      name: 'aweqweqjm',
      address: 'vbrfyhs',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'dial-d-for-deadman',
      name: 'wyetsdgs',
      address: 'vcxvsghs',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'talk-about-race',
      name: 'asfxzcvzxc',
      address: 'bfgjftfg',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'the-testaments',
      name: 'asdfzxczx',
      address: 'hfgjhfgj',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'will-save-the-galaxy',
      name: 'gsdgsdg',
      address: 'gfjfg',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'storm-front',
      name: 'dsgscxv',
      address: 'xcbxcbxb',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'hard-luck-hank',
      name: 'qaseasd',
      address: 'vxcvxcv',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'andrew-vernon-1',
      name: 'bcvbcvb',
      address: 'xzcaqsd',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'andrew-vernon-2',
      name: 'bcvbqweqwcvb',
      address: 'xzcaqwr',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'off-to-be-the-wizard',
      name: 'qwtqw',
      address: 'fsdfasf',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'master-of-formalities',
      name: 'qweqwe',
      address: 'gsddfg',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'the-authorities',
      name: 'qweqwe',
      address: 'hkghk',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'expanse-1',
      name: 'qweqaweqwe',
      address: 'hkghdfgdfk',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'expanse-2',
      name: 'ghikghi',
      address: 'asdasd',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'anansi-boys',
      name: 'ghiktyoghi',
      address: 'asdqwrqasd',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'fuzzy-nation',
      name: 'asdqwe',
      address: 'sqdasd',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'ghost-in-the-wires',
      name: 'wqsdasd',
      address: 'asdqwe',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'a-brief-history',
      name: 'sdgsdgsd',
      address: 'qwetfivhkl',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'killing-floor',
      name: 'asdqawe',
      address: 'asdfqtwe',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'darkness',
      name: 'qweaxdas',
      address: 'qwezdfsad',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'neuromancer',
      name: 'dhcbvc',
      address: 'qweasc',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: '14',
      name: 'dhcbvcqwrsf',
      address: 'qweaqwrqwsc',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'martian',
      name: 'asdxcv',
      address: 'qweZx',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
  ],
};
