
export default {
  blcos: [
    {
      id: 'dear-girls',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'utterly',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'angry-planet',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'technically-wrong',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'orconomics',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'dial-d-for-deadman',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'talk-about-race',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'the-testaments',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'will-save-the-galaxy',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'storm-front',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'hard-luck-hank',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'andrew-vernon-1',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'andrew-vernon-2',
      address: '',
      lat: '',
      lng: '',
    },
    {
      id: 'off-to-be-the-wizard',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'master-of-formalities',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'the-authorities',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'expanse-1',
      address: '',
      lat: '',
      lng: '',
    },
    {
      id: 'expanse-2',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'anansi-boys',
      address: '',
      lat: '',
      lng: '',
    },
    {
      id: 'fuzzy-nation',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'ghost-in-the-wires',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'a-brief-history',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'killing-floor',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'darkness',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: 'neuromancer',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
    {
      id: '14',
      address: '',
      lat: '',
      lng: '',
    },
    {
      id: 'martian',
      name: '',
      address: '',
      lat: '',
      lng: '',
      admId: '',
      admName: '',
    },
  ],
};
